version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
      - yarn add rimraf
  build:
    commands:
      - echo Build started on `date`
      - echo '{"mongo":{"url":"mongodb+srv://username:password@cluster0.pc6hv.mongodb.net/<dbname>"},"rateLimit":{"windowMS":15000,"count":1000}}' >> config.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
