version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Yarn...
      - npm install -g yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo "TODO: Need to run tests here"
  post_build:
    commands:
      - echo Build completed on `date`